use indexmap::IndexMap;
use serde::Deserialize;
use serde_json::Value;

// The other members of the notebook are not needed, so we pretend they don't exist.
// If we wanted to write notebooks with this code, we would have to add them back.

/// The root of the JSON of a Jupyter Notebook
///
/// Generated by <https://app.quicktype.io/> from
/// <https://github.com/jupyter/nbformat/blob/16b53251aabf472ad9406ddb1f78b0421c014eeb/nbformat/v4/nbformat.v4.schema.json>
/// Jupyter Notebook v4.5 JSON schema.
#[derive(Clone, Debug, Deserialize)]
pub struct RawNotebook {
    /// Array of cells of the current notebook.
    pub cells: Vec<Cell>,
    // /// Notebook root-level metadata.
    // pub metadata: Value,
    // /// Notebook format (major number). Incremented between backwards incompatible changes to the
    // /// notebook format.
    // pub nbformat: i64,
    // /// Notebook format (minor number). Incremented for backward compatible changes to the
    // /// notebook format.
    // pub nbformat_minor: i64,
}
// By assigning unit variants to these, we can avoid parsing them. Nice!

/// String identifying the type of cell.
#[derive(Debug, Deserialize, Clone)]
#[serde(tag = "cell_type")]
pub enum Cell {
    #[serde(rename = "code")]
    Code(CodeCell),
    #[serde(rename = "markdown")]
    Markdown,
    #[serde(rename = "raw")]
    Raw,
}

impl Cell {
    pub const fn get_code_cell(&self) -> Option<&CodeCell> {
        match self {
            Self::Code(cell) => Some(cell),
            _ => None,
        }
    }
}

/// Notebook code cell.
#[derive(Clone, Debug, Deserialize)]
pub struct CodeCell {
    // /// The id may or may not be present
    // pub id: Option<String>,
    /// Cell-level metadata.
    pub metadata: CellMetadata,
    /// Execution, display, or stream outputs.
    pub outputs: Vec<Output>,
    pub source: SourceValue,
}
impl CodeCell {
    pub fn get_output_data(&self) -> Vec<&MimeBundle> {
        self.outputs
            .iter()
            .filter_map(|x| x.get_display_data())
            .collect()
    }
}

#[derive(Clone, Debug, Deserialize)]
pub struct CellMetadata {
    /// Cell tags. We look for the image name here. They are actually supposed to be unique but we don't need to validate that, hence "Vec"
    pub tags: Option<Vec<String>>,
}

/// Result of executing a code cell.
/// String identifying the type of cell output.
#[derive(Debug, Deserialize, Clone)]
#[serde(tag = "output_type")]
pub enum Output {
    #[serde(rename = "display_data")]
    DisplayData(DisplayDataOut),
    #[allow(dead_code)]
    #[serde(rename = "error")]
    Error,

    #[serde(rename = "execute_result")]
    ExecuteResult(ExecuteResultOut),

    #[allow(dead_code)]
    #[serde(rename = "stream")]
    Stream,
}

impl Output {
    const fn get_display_data(&self) -> Option<&MimeBundle> {
        match self {
            Self::DisplayData(out) => Some(&out.data),
            Self::ExecuteResult(out) => Some(&out.data),
            _ => None,
        }
    }
}

/// mimetype output (e.g. text/plain), represented as either an array of strings or a
/// string.
///
/// Contents of the cell, represented as an array of lines.
///
/// The stream's text output, represented as an array of strings.
#[derive(Debug, Deserialize, Clone)]
#[serde(untagged)]
pub enum SourceValue {
    String(String),
    StringArray(Vec<String>),
    // If the media type string ends with json, the contents can be anything. e.g. with widgets
    // this variant has to go last, because with untagged unions, the variants are tried in order.
    // We won't enforce that the media type string ends with json
    #[allow(dead_code)]
    JsonData(Value),
}
// IndexMap preserves the notebook's mime-type order, so extraction (and the
// -1/-2 numbering of multi-image cells) is deterministic
pub type MimeBundle = IndexMap<String, SourceValue>;

impl SourceValue {
    pub fn to_string_array(&self) -> Option<Vec<&str>> {
        match self {
            Self::JsonData(_) => None,
            Self::StringArray(sa) => Some(sa.iter().map(std::string::String::as_str).collect()),
            Self::String(s) => Some(s.split_inclusive('\n').collect()),
        }
    }
}

#[derive(Debug, Deserialize, Clone)]
pub struct DisplayDataOut {
    pub data: MimeBundle,
    // pub metadata: OutputMetadata,
}

#[derive(Debug, Deserialize, Clone)]
pub struct ExecuteResultOut {
    pub data: MimeBundle,
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;
    use serde_json::json;

    fn source_value(v: Value) -> SourceValue {
        serde_json::from_value(v).unwrap()
    }

    #[test]
    fn source_value_deserializes_untagged_variants_in_order() {
        assert!(matches!(source_value(json!("s")), SourceValue::String(_)));
        assert!(matches!(
            source_value(json!(["a"])),
            SourceValue::StringArray(_)
        ));
        assert!(matches!(
            source_value(json!({"k": 1})),
            SourceValue::JsonData(_)
        ));
        assert!(matches!(source_value(json!(3)), SourceValue::JsonData(_)));
    }

    #[test]
    fn to_string_array_splits_string_keeping_newlines() {
        let sv = source_value(json!("a\nb\nc"));
        assert_eq!(sv.to_string_array(), Some(vec!["a\n", "b\n", "c"]));
        let sv = source_value(json!("a\n"));
        assert_eq!(sv.to_string_array(), Some(vec!["a\n"]));
    }

    #[test]
    fn to_string_array_passes_through_string_array() {
        let sv = source_value(json!(["x", "y"]));
        assert_eq!(sv.to_string_array(), Some(vec!["x", "y"]));
    }

    #[test]
    fn to_string_array_is_none_for_json_data() {
        let sv = source_value(json!({"model_id": "abc"}));
        assert_eq!(sv.to_string_array(), None);
    }

    #[test]
    fn get_code_cell_filters_cell_types() {
        let markdown: Cell = serde_json::from_value(json!({
            "cell_type": "markdown",
            "metadata": {},
            "source": "# heading"
        }))
        .unwrap();
        assert!(markdown.get_code_cell().is_none());

        let code: Cell = serde_json::from_value(json!({
            "cell_type": "code",
            "metadata": {},
            "outputs": [],
            "source": "x = 1"
        }))
        .unwrap();
        assert!(code.get_code_cell().is_some());
    }

    #[test]
    fn get_output_data_keeps_only_data_outputs() {
        let cell: CodeCell = serde_json::from_value(json!({
            "metadata": {},
            "source": "plot()",
            "outputs": [
                {"output_type": "stream", "name": "stdout", "text": ["hi\n"]},
                {"output_type": "display_data", "data": {"image/png": "AAAA"}, "metadata": {}},
                {"output_type": "error", "ename": "E", "evalue": "boom", "traceback": []},
                {"output_type": "execute_result", "data": {"text/plain": "1"}, "metadata": {}, "execution_count": 1}
            ]
        }))
        .unwrap();
        let data = cell.get_output_data();
        assert_eq!(data.len(), 2);
        assert!(data[0].contains_key("image/png"));
        assert!(data[1].contains_key("text/plain"));
    }

    #[test]
    fn parses_example_notebook() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/example.ipynb");
        let file = std::fs::File::open(path).unwrap();
        let nb: RawNotebook = serde_json::from_reader(std::io::BufReader::new(file)).unwrap();
        assert_eq!(nb.cells.len(), 13);
        let n_code = nb
            .cells
            .iter()
            .filter(|c| c.get_code_cell().is_some())
            .count();
        assert_eq!(n_code, 10);
    }
}
